spring.datasource.url=jdbc:mysql://localhost:3306/rishtabox
spring.datasource.username=root
spring.datasource.password=@Shahid9341

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=rishtabox-backend
server.port=8080
jwt.secret=RishtaBoxSuperSecretKeyForJwtAuthentication2026
jwt.expiration=86400000