spring.datasource.url=jdbc:mysql://localhost:3306/rishtabox
spring.datasource.username=root
spring.datasource.password=@Shahid9341

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=rishtabox-backend
server.port=8080
jwt.secret=RishtaBoxSuperSecretKeyForJwtAuthentication2026
jwt.expiration=86400000
razorpay.key.id=rzp_live_T993YlUbiXqvXZ
razorpay.key.secret=1pweGxz9NXn73m8Qyexmovmz
shiprocket.base-url=https://apiv2.shiprocket.in
shiprocket.email=puchoonline44@gmail.com
shiprocket.password=ArkN7@5A093VihBB!EETU9&11@8rT8Uv

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mdshahidans2005@gmail.com
spring.mail.password=tkpqzguypexgfyxz

spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.debug=true
rishtabox.slider.upload-dir=C:/Users/MD SHAHID ANSARI/RishtaBox/Frontend/uploads/sliders

rishtabox.category.upload-dir=C:/Users/MD SHAHID ANSARI/RishtaBox/Frontend/uploads/categories

rishtabox.festival.upload-dir=C:/Users/MD SHAHID ANSARI/RishtaBox/Frontend/uploads/festivals

rishtabox.relationship.upload-dir=C:/Users/MD SHAHID ANSARI/RishtaBox/Frontend/uploads/relationships

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB